name: Build e Deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: curriculum-api
  SERVICE_NAME: curriculum-api
  CONTAINER_PORT: 8080
  HOST_PORT: 8080

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código fonte
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Criar arquivos de chave JWT
      run: |
        echo "${{ secrets.JWT_PRIVATE_KEY }}" > app.key
        echo "${{ secrets.JWT_PUBLIC_KEY }}" > app.pub
        mkdir -p src/main/resources
        mv app.key app.pub src/main/resources/

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build e testes
      run: mvn -B verify --file pom.xml

    - name: Login no GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login $REGISTRY -u ${{ github.repository_owner }} --password-stdin

    - name: Build e push da imagem Docker
      run: |
        docker buildx create --use
        docker buildx build \
          -t $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }} \
          --push .

    - name: Clone do repositório GitOps
      uses: actions/checkout@v3
      with:
        repository: marcuslinhares/curriculum-gitops
        ref: main
        token: ${{ secrets.GITOPS_TOKEN }}
        path: gitops

    - name: Atualizar tag da imagem no deployment.yaml
      run: |
        cd gitops/dev/backend-app
        sed -i "s|image: ghcr.io/.*/curriculum-api:.*|image: ghcr.io/${{ github.repository_owner }}/curriculum-api:${{ github.sha }}|" deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add deployment.yaml
        git commit -m "Atualiza imagem curriculum-api para ${{ github.sha }}"
        git push origin main
