name: Build e Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: curriculum-api
  IMAGE_TAG: latest
  SERVICE_NAME: curriculum-api
  CONTAINER_PORT: 8080
  HOST_PORT: 8080

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Build da imagem Docker
      run: |
        docker build -t $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG .

    - name: Login no GHCR com token pessoal
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login $REGISTRY -u ${{ github.repository_owner }} --password-stdin

    - name: Push da imagem
      run: |
        docker push $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG

    - name: SSH na VPS e fazer deploy com Docker Swarm
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        envs: REGISTRY,IMAGE_NAME,IMAGE_TAG,SERVICE_NAME,CONTAINER_PORT,HOST_PORT
        script: |

          docker service create \
            --name $SERVICE_NAME \
            --replicas 1 \
            --publish $HOST_PORT:$CONTAINER_PORT \
            --env CURRICULUM_DB_URL=${{ secrets.CURRICULUM_DB_URL }} \
            --env CURRICULUM_DB_USERNAME=${{ secrets.CURRICULUM_DB_USERNAME }} \
            --env CURRICULUM_DB_PASSWORD=${{ secrets.CURRICULUM_DB_PASSWORD }} \
            --env ADMIN_NOME=${{ secrets.ADMIN_NOME }} \
            --env ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
            --env ADMIN_SENHA=${{ secrets.ADMIN_SENHA }} \
            --env AMBIENTE=${{ secrets.AMBIENTE }} \
            --env JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }} \
            --env JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }} \
            --env PRODURL=${{ secrets.PRODURL }} \
            $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG
